apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devopardy-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: devopardy.devopswithbrian.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: devopardy-ui
            port:
              number: 80