apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devopardy-ui-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
spec:
  tls:
  - hosts:
    - devopardy.devopswithbrian.com
    - devopardy-api.devopswithbrian.com
    secretName: devopardy-tls
  rules:
  - host: devopardy.devopswithbrian.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: devopardy-ui
            port:
              name: devopardy-ui
  - host: devopardy-api.devopswithbrian.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: devopardy-api
            port:
              name: devopardy-api
      