apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopardy-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopardy-ui
  template:
    metadata:
      labels:
        app: devopardy-ui
    spec:
      containers:
      - name: devopardy-ui
        image: devopswithbrian/devopardy-ui:1.4.0
        env:
          - name: REACT_APP_API_URL
            valueFrom:
              secretKeyRef:
                name: devopardy-prd
                key: REACT_APP_API_URL
        ports:
        - containerPort: 3000