apiVersion: v1
kind: Service
metadata:
  name: devopardy-ui
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-default-protocol: http
    service.beta.kubernetes.io/linode-loadbalancer-port-443: '{ "letsencrypt-prod", "protocol": "https" }'
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: devopardy-ui
		